name: Build & Test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Runs on pull requests targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: DoozyX/clang-format-lint-action@v0.17

  python-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: psf/black@stable

  deploy:
    runs-on: ubuntu-latest
    container: ubuntu:lunar
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Update repos
        run: apt update
      - name: Install dependencies
        run: apt install -y git meson libgirepository1.0-dev dbus libdbus-glib-1-dev python3-dasbus python3-tap python3-gi libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good
      - name: Set up permissions
        run: chown ubuntu:ubuntu .
      - name: Setup Spiel
        run: su ubuntu -c "meson setup build -Ddocs=false"
      - name: Compile Spiel
        run: su ubuntu -c "meson compile -C build"
      - name: Test Spiel
        run: su ubuntu -c "meson test -C build"
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Meson_Testlog
          path: build/meson-logs/testlog.txt

  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/actuary:latest

    strategy:
      matrix:
        compiler: [gcc, llvm]
        suite: [test, asan, analyzer]
        include:
          - suite: test
            setup-args: |
              -Ddocs=false
              -Dintrospection=true
              -Dtests=true
            test-args: |
              --repeat=3
          - suite: asan
            setup-args: |
              -Ddocs=false
              -Dintrospection=false
              -Dtests=true
          - suite: analyzer
            setup-args: |
              -Ddocs=false
              -Dtests=true
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Prepare
        run: |
          dnf install -y cairo-gobject-devel dbus-glib-devel python3.11 python3.11-devel python3-dasbus python3-gobject-devel gi-docgen gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-plugins-good
          python3.11 -m ensurepip --upgrade
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install dasbus dbus-python PyGObject tap.py

      - name: Test
        id: test
        uses: andyholmes/actuary@main
        with:
          suite: ${{ matrix.suite }}
          compiler: ${{ matrix.compiler }}
          setup-args: ${{ matrix.setup-args }}
          test-args: ${{ matrix.test-args }}
          test-coverage: ${{ matrix.compiler == 'gcc' && matrix.suite == 'test' }}
          lcov-include: 'libspeechprovider libspiel utils'
          lcov-exclude: 'tests'

      - name: Test Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Tests (${{ matrix.compiler }}, ${{ matrix.suite }})
          path: ${{ steps.test.outputs.log }}

      - name: Coverage (html)
        if: ${{ matrix.compiler == 'gcc' && matrix.suite == 'test' }}
        uses: actions/upload-artifact@v4
        with:
          name: Tests (coverage)
          path: ${{ steps.test.outputs.coverage-html }}
